### PR TITLE
Run PVS-Studio over tinyusdz library and fix found issues

### PR DESCRIPTION
**Pull request by dimhotepus**
Product page: https://www.viva64.com/en/pvs-studio/
How to use for free: https://www.viva64.com/en/b/0600/

### CODE REVIEW

**Comment by syoyo** [comment]
Oh nice! Fixes are also applied to third-party codes. Is it possible to split PR into three components?(external(tinyexr),  opensubdiv, and tinyusdz itself)

**Comment by dimhotepus** [comment]
> Oh nice! Fixes are also applied to third-party codes. Is it possible to split PR into three components?(external(tinyexr), opensubdiv, and tinyusdz itself)

Done, I've stored only tinyusdz fixes here.

**Comment by syoyo** [comment]
@dimhotepus Thanks! Let me give some time to review fixes.

**Comment by syoyo** [comment]
@dimhotepus Merged! Thank you! :pray:

**Pull request merged**
