### PR TITLE
added CompositeVariantWithCallback

### PR DESCRIPTION
**Pull request by rdeioris**
This patch adds a CompositeVariantWithCallback function allowing to define which variant to load during composition based on a custom callback:

```cpp
bool VariantSelectionCallback(const tinyusdz::PrimSpec& PrimSpec, std::map<std::string, std::string>* VariantSelection, std::string* Warnings, std::string* Errors, void* UserData) {
  // fill VariantSelection map
}
```

### CODE REVIEW

**Comment by syoyo** [comment]
Please describe the purpose of this PR

**Comment by rdeioris** [comment]
Sure, you are right:

Composition process (at least in the current implementation) is a very recursive operation, where actually you should traverse all of the PrimSpec "discovered" by a composition step (like references or inheritance resolution) and check if a new variantset is available (and eventually overwrite the PrimSpec to select the wanted variant).

This makes "generalization" of variants management pretty hard (you need to inject your logic after every step of composition, or you need to apply all of the composition steps except variants and do everything at the end, potentially triggering another round of references resolution caused by a specific variant).

The proposed function allows the user that knows from the begining which variant to apply (and this is pretty common for runtime loaders) to apply on the fly during the recursive process (like in tusdcat)

As an example if i know from the beginnign that i want the "HighDef" variant for all of the PrimSpec i can simply have simple callback setting it on the fly:

```cpp
bool VariantSelectionCallback(const tinyusdz::PrimSpec& PrimSpec, std::map<std::string, std::string>* VariantSelection, std::string* Warnings, std::string* Errors, void* UserData) {
  for(const auto& pair : PrimSpec.variantSets())
  {
    (*VariantSelection)[pair.first] = "HighDef";
  }
}
```

**Comment by syoyo** [comment]
> The proposed function allows the user that knows from the begining which variant to apply 

AFAIK I have prepared `ApplyVariantSelector` for that purpose(no implementation yet)

https://github.com/lighttransport/tinyusdz/blob/2a30dd7f63699ac539c070bcefef5a60c4a7ff56/src/composition.hh#L256

So I guess implementing `ApplyVariantSelector` will be a preferred way instead of providing callback function.

Also it  is better to submit an issue or raise a discussion(in "Discussion" pane https://github.com/lighttransport/tinyusdz/discussions ) before sending a PR if you add new feature.

**Comment by rdeioris** [comment]
@syoyo thanks for the hint, going to close it end i will send a pull request for ApplyVariantSelector

**Pull request closed without merging**
