### PR TITLE
Improved subLayers compositionarc

### PR DESCRIPTION
**Pull request by rdeioris**
This patch attempts to fix the issue reported here: https://github.com/lighttransport/tinyusdz/issues/207

It adds a new function CombinePrimSpecRec that is used instead of OverridePrimSpec. This is required as sublayers composition assumes a different logic (it is not a true override, as only missing properties and children are applied).

In addition to this recursiveness is now supported.

### CODE REVIEW

**Comment by syoyo** [comment]
Thanks! PR seems OK!

Could you please add test files under `tests/usda/composition`? Example is https://github.com/lighttransport/tinyusdz/commit/fb66ca57231d7efae3415cb5112f63bcc929a63d

**Comment by rdeioris** [comment]
@syoyo yep, sorry for the late, i will do it asap, thanks!

**Comment by rdeioris** [comment]
@syoyo done. I have noticed that the composition directory is not managed in tests. I am going to open a discussion for it. Thanks

**Comment by syoyo** [comment]
Thanks! Merged!

There is a Windows ARM32 build issue, but this is an issue of CI build env. We can ignore it for a while.

**Pull request merged**
